// @ts-check
import { defineConfig, globalIgnores } from "eslint/config";
import js from "@eslint/js";
import stylistic from "@stylistic/eslint-plugin";
import tseslint from "typescript-eslint";
import tsParser from "@typescript-eslint/parser";

export default defineConfig([
  // Besides ESLint's default `**/*.js`, `**/*.cjs`, and `**/*.mjs` lint also
  // TypeScript files:
  {
    files: ["**/*.ts"]
  },
  {
    plugins: {
      js,
    },
    extends: ["js/recommended"],
    rules: {
      "array-callback-return": ["error", { "checkForEach": true }],
      "no-constructor-return": "error",
      "no-duplicate-imports": [
        "error",
        {
          "includeExports": true,
          "allowSeparateTypeImports": true,
        },
      ],
      "no-inner-declarations": [
        "error",
        "both",
        { blockScopedFunctions: "disallow" },
      ],
      "no-promise-executor-return": "error",
      "no-template-curly-in-string": "error",
      "no-unmodified-loop-condition": "error",
      "no-unreachable-loop": "error",
      "no-use-before-define": "error",
      "require-atomic-updates": "error",
      // Suggestions:
      "block-scoped-var": "error",
      "camelcase": "error",
      "capitalized-comments": "error",
      "class-methods-use-this": "error",
      "complexity": ["error", 10],
      "consistent-return": "error",
      "consistent-this": "error",
      "curly": ["error", "multi-or-nest"],
      "default-case": "error",
      "default-case-last": "error",
      "default-param-last": "error",
      "dot-notation": "error",
      "eqeqeq": "error",
      "func-name-matching": ["error", { "considerPropertyDescriptor": true }],
      "func-style": "error",
      "grouped-accessor-pairs": "error",
      "guard-for-in": "error",
      "init-declarations": "error",
      "logical-assignment-operators": [
        "error",
        { enforceForIfStatements: true },
      ],
      "max-depth": "error",
      "max-lines-per-function": [
        "error",
        {
          "skipBlankLines": true,
          "skipComments": true,
        },
      ],
      "max-nested-callbacks": ["error", 3],
      "max-params": ["error", 5],
      "max-statements": "error",
      "new-cap": "error",
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-bitwise": "error",
      "no-caller": "error",
      "no-div-regex": "error",
      "no-else-return": "error",
      "no-empty-function": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-boolean-cast": [
        "error",
        { "enforceForInnerExpressions": true },
      ],
      "no-extra-label": "error",
      "no-implied-eval": "error",
      "no-inline-comments": "error",
      "no-iterator": "error",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-magic-numbers": [
        "error",
        {
          "ignore": [-1, 0, 1],
          "ignoreArrayIndexes": true,
          "enforceConst": true,
          "ignoreEnums": true,
          "ignoreTypeIndexes": true,
        },
      ],
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-object-constructor": "error",
      "no-octal-escape": "error",
      "no-param-reassign": "error",
      "no-proto": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-sequences": "error",
      "no-shadow": [
        "error",
        {
          "builtinGlobals": true,
          "hoist": "all",
        },
      ],
      "no-throw-literal": "error",
      "no-undef-init": "error",
      "no-undefined": "error",
      "no-underscore-dangle": "error",
      "no-unneeded-ternary": "error",
      "no-unused-expressions": "error",
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "no-void": "error",
      "no-warning-comments": "error",
      "object-shorthand": "error",
      "one-var": ["error", "never"],
      "operator-assignment": "error",
      "prefer-arrow-callback": "error",
      "prefer-const": "error",
      "prefer-destructuring": "error",
      "prefer-exponentiation-operator": "error",
      "prefer-named-capture-group": "error",
      "prefer-numeric-literals": "error",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-regex-literals": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "radix": "error",
      "require-await": "error",
      "require-unicode-regexp": "error",
      "sort-imports": "error",
      "strict": "error",
      "symbol-description": "error",
      "vars-on-top": "error",
      "yoda": "error",
      // Layout && Formatting:
      "unicode-bom": "error",
    },
  },
  tseslint.configs.strictTypeChecked,
  tseslint.configs.stylisticTypeChecked,
  {
    plugins: {
      "@stylistic": stylistic,
    },
    languageOptions: {
      parser: tsParser,
    },
    extends: [stylistic.config.customize({ semi: true })],
    rules: {
      "@stylistic/max-len": ["error", { "code": 79 }],
      "@stylistic/no-extra-semi": "error",
    },
  },
  globalIgnores(["**/.git", "**/node_modules"]),
]);
